name: SASS CI
  
on:
  workflow_call:
    inputs:
      sass-folder:
        description: The folder containing the SASS
        required: true
        type: string
        
      upload-artifact:
        description: Upload the created CSS
        required: false
        default: false
        type: boolean
  
jobs: 
  build-css:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Make directory for css
        run: mkdir -vp css
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Install SASS
        run: npm install -g sass    
        
      - name: Compile css
        run: sass ${{ inputs.sass-folder }}:css
        
  upload-css:
    needs: build-css
    if: inputs.upload-artifact
    runs-on: ubuntu-latest
    
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: compiled-css
          path: css
