name: Django CI

on:
  workflow_call:
    inputs:
      project-root:
        description: The root folder of the Django site
        required: true
        type: string
  
jobs:
  test:
    name: Test Django Site
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        continue-on-error: true
        run: |
          cat requirements.txt | xargs -n 1 pip install

      - name: Run Tests
        env:
          SECRET_KEY: test-key-insecure
          DEBUG: True
          ALLOWED_HOSTS: "*"
          CSRF_TRUSTED_ORIGINS: "http://*"
          FILE_ROOT: ${{ inputs.project-root }}/files
        run: python3.10 ${{ inputs.project-root }}/manage.py test
