name: Django CI

on:
  workflow_call:
    inputs:
      project-root:
        description: The root folder of the Django site
        required: true
        type: string
      env:
        description: The environment variables as a json object surrounded by quotes
        required: false
        type: string
  
jobs:
  test:
    name: Test Django Site
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Run setup commands
        run: bash ci-setup.sh

      - name: Install requirements
        #continue-on-error: true
        #run: cat requirements.txt | xargs -n 1 pip install
        run: pip install -r requirements.txt

      - name: Run Tests
        env:
          SECRET_KEY: test-key-insecure
          DEBUG: True
          ALLOWED_HOSTS: "*"
          CSRF_TRUSTED_ORIGINS: "http://*"
          FILE_ROOT: ${{ inputs.project-root }}/files
          DEPLOY_USER: Spartan2909
          DEPLOY_TOKEN: 336b2ea8423ea3ee562bea7bb35c393080cfc044
          DEPLOY_HOST: www.pythonanywhere.com
          DEPLOY_URL: spartan2909.pythonanywhere.com
        run: python3.10 ${{ inputs.project-root }}/manage.py test
