on:
  workflow_call:
  
 jobs:
   tsc:
     name: tsc
     runs-on: ubuntu-latest
     
     steps:
     - uses: actions/checkout@v3
     
     - name: install node
       uses: actions/setup-node@v3
       with:
         node-version: "*"
         check-latest: true
         
     - name: install yarn
       run: yarn install
       
     - name: compile typescript
       uses: icrawl/action-tsc@v1
